name: Kotlin CI - macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Kotlin Compiler
      run: |
        brew install kotlin

    - name: Compile and Run Kotlin files
      run: |
        SOURCES=$(find src/core -name "*.kt" | tr '\n' ' ')
        
        if [ ! -z "$SOURCES" ]; then
          kotlinc $SOURCES -include-runtime -d app.jar
          java -jar app.jar
        fi

