name: Kotlin CI - macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Kotlin Compiler
      run: |
        brew install kotlin

    - name: Compile and Run Kotlin files recursively
      run: |
        find src -name "*.kt" > sources.txt
        if [ -s sources.txt ]; then
          kotlinc -script $(cat sources.txt)
        fi
