name: Kotlin CI - Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Kotlin Compiler
      run: |
        choco install kotlin -y

    - name: Compile and Run Kotlin files recursively
      shell: powershell
      run: |
        $files = Get-ChildItem -Path src -Filter *.kt -Recururse | Select-Object -ExpandProperty FullName
        if ($files) {
            foreach ($file in $files) {
                kotlinc -script $file
            }
        }
